runtime: nodejs
env: flex

env_variables:
  FACEBOOK_CALLBACK_URL: 'https://car-pool-001.appspot.com/auth/facebook/callback'

manual_scaling:
  instances: 1

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
